# -*- coding: utf-8 -*-
"""Week1_Sales Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hx0b_hs9U-QVi3vTsesT5123BbO_9Yqc

**Sales Data Analysis**
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Stores.csv")

print("Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)

store_id = df["Store ID"].to_numpy()
store_area = df["Store_Area"].to_numpy()
items_available = df["Items_Available"].to_numpy()
daily_customers = df["Daily_Customer_Count"].to_numpy()
store_sales = df["Store_Sales"].to_numpy()

print("Store ID :")
print(store_id)
print("Store Area :")
print(store_area)
print("Items Available :")
print(items_available)
print("Daily Customers :")
print(daily_customers)
print("Store Sales :")
print(store_sales)

total_sales = np.sum(store_sales)
average_sales = np.mean(store_sales)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)

user_input = int(input("Enter a Store ID: "))

index_result = df[df['Store ID'] == user_input]

if not index_result.empty:
    print(index_result)
else:
    print("Store ID not found")

print()

start = int(input("Enter the start index: "))
end = int(input("Enter the end index: "))

slice_result = df[(df['Store ID'] >= start) & (df['Store ID'] <= end)]
print(slice_result)

print("Mean:", np.mean(store_sales))
print("Median:", np.median(store_sales))
print("Variance:", np.var(store_sales))
print("Standard Deviation:", np.std(store_sales))

df['Revenue'] = df['Store_Sales'] * df['Items_Available']
print(df[['Store ID', 'Revenue']])

user_input = int(input("Enter Store ID: "))

result = df[df['Store ID'] == user_input]

if not result.empty:
    revenue = result['Store_Sales'] * result['Items_Available']
    print("Revenue for Store ID", user_input, ":", revenue.values[0])
else:
    print("Store ID not found")