# -*- coding: utf-8 -*-
"""Week2_Titanic Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhebDDizkc5KFdgVBoTrR4PrLq63_1hp
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Titanic.csv')

print("Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)
print("\n Sample Output")
df.head()

passenger_id = df['PassengerId'].to_numpy()
survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()
name = df['Name'].to_numpy()
sex = df['Sex'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
ticket = df['Ticket'].to_numpy()
fare = df['Fare'].to_numpy()
cabin = df['Cabin'].to_numpy()
embarked = df['Embarked'].to_numpy()

print(df.to_string())

df.head()
df.info()
df.describe()

df.isnull().sum()

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df.drop(columns=["Cabin"], inplace=True)
df.isnull().sum()

df.loc[10, ["Name", "Age", "Fare", "Survived"]]

df.iloc[5:10, [0, 2, 4, 6]]

df.rename(columns={"Sex": "Gender"}, inplace=True)
df.head()

pivot_table = df.pivot_table(values="Survived", index="Pclass", columns="Gender", aggfunc="mean")
print(pivot_table)

df[df["Age"] > 30]

df[df["Fare"] > 50]

df[(df["Gender"] == "female") & (df["Survived"] == 1)]

df.sort_values(by="Fare", ascending=False)

df.groupby("Gender")["Survived"].mean()

df.groupby("Pclass")["Age"].mean()

df.groupby("Embarked")["Survived"].sum()

extra_df = pd.DataFrame({
    "Pclass": [1, 2, 3],
    "Category": ["Luxury", "Standard", "Economy"]
})

merged_df = pd.merge(df, extra_df, on="Pclass", how="left")
print(merged_df[["Pclass", "Category"]].head())

extra_info = pd.DataFrame({
    "PassengerId": [1, 2, 3],
    "VIP": [True, False, False]
}).set_index("PassengerId")

df.set_index("PassengerId", inplace=True)

joined_df = df.join(extra_info)
print(joined_df[["Name", "VIP"]].head())

df_part1 = df.iloc[:500]
df_part2 = df.iloc[500:]

concat_df = pd.concat([df_part1, df_part2])
print(concat_df.shape)

df.groupby("Survived")["Age"].mean()

df["Fare"].max(), df["Fare"].min()

(df["Survived"].sum() / len(df)) * 100