# -*- coding: utf-8 -*-
"""Week3_Weather_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rngQG_dKzphRQjNizArwo1vARTCXgjq
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/weather_data.csv")

print("Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)
print("\n Sample Output")
df.head()

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)

df['Date_Time'] = pd.to_datetime(df['Date_Time'])
df['Month'] = df['Date_Time'].dt.month

def get_season(month):
    if month in [12,1,2]:
        return "Winter"
    elif month in [3,4,5]:
        return "Summer"
    elif month in [6,7,8]:
        return "Monsoon"
    else:
        return "Autumn"

df['Season'] = df['Month'].apply(get_season)

print("Shape:", df.shape)
print("\nColumn Names:")
print(df.columns)
print("\n Sample Output")
df.head()

df['Date'] = df['Date_Time'].dt.date
daily_temp = df.groupby('Date')['Temperature_C'].mean()

plt.figure()

plt.plot(daily_temp.index, daily_temp.values)

plt.title("Daily Average Temperature Trend")
plt.xlabel("Date")
plt.ylabel("Temperature (°C)")

plt.show()

season_rain = df.groupby('Season')['Precipitation_mm'].mean()

season_rain.plot(kind='bar')

plt.title("Average Rainfall by Season")
plt.xlabel("Season")
plt.ylabel("Rainfall (mm)")

plt.show()

plt.hist(df['Temperature_C'], bins=20)

plt.title("Temperature Distribution")
plt.xlabel("Temperature")
plt.ylabel("Frequency")

plt.show()

plt.scatter(df['Temperature_C'], df['Humidity_pct'])

plt.title("Temperature vs Humidity")
plt.xlabel("Temperature")
plt.ylabel("Humidity")

plt.show()

season_counts = df['Season'].value_counts()

plt.pie(season_counts, labels=season_counts.index, autopct='%1.1f%%')

plt.title("Season Distribution")

plt.show()